name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install neccessary commands (judger)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y auditd flex make gengetopt bison xxd strace
    - name: Install LLVM and Clang (judger)
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "13"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Generate
      run: go generate -v ./pkg/...
    - name: Build
      run: go build -v ./pkg/...
    - name: Test
      run: |
        go test -v ./pkg/...
        go test -v ./test
